DROP TABLE IF EXISTS `MovieGenre`;
DROP TABLE IF EXISTS `MovieDirector`;
DROP TABLE IF EXISTS `MovieActor`;
DROP TABLE IF EXISTS `Review`;

DROP TABLE IF EXISTS `Movie`;
DROP TABLE IF EXISTS `Actor`;
DROP TABLE IF EXISTS `Director`;

DROP TABLE IF EXISTS `MaxPersonID`;
DROP TABLE IF EXISTS `MaxMovieID`;